New repo structure with packages: move config & logger to packages, leave gateway at /src
code-store-platform/graphql-portal pull request #14
Opened 2020-12-16 20:38 UTC by valcker

We now have a new structure with packages:
/packages/* – things which we have to reuse
/src/ – gateway itself (we might move it to gateway too).

It two words it works like the following:
- we've got a parent tsconfig.json which defines that it references 2 packages (see "references" in tsconfig.json)
- each package has its own tsconfig.json which extends the parent one
- we are also using yarn workspaces (see "workspaces" in package.json)
- in order to fix the problem with module aliases, we have to define "paths" to our packages in the parent tsconfig
- in order to build the project we are running tsc -b in the root folder, this will build all of the packages defined in "references".

2020-12-16 20:59 UTC, Feshchenko approved these changes

2020-12-17 12:38 UTC, germankrause requested changes

2020-12-17 12:38 UTC, germankrause commented on packages/config/src/index.ts
> +// import { prefixLogger } from '../../../src/logger';
should it be `import { logger } from '@graphql-portal/logger';?

2020-12-17 14:48 UTC, germankrause approved these changes

2020-12-17 14:48 UTC, merged